apiVersion: v1
kind: Pod
metadata:
  name: gin-server
  labels:
    app: go
spec:
  containers:
  - name: gin-server
    image: changsiheng/gin-server:week3
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
    ports:
      - containerPort: 8080
        name: http-go-svc
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: http-go-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - golearn.com
      secretName: golearn-tls
  rules:
    - host: golearn.com
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: go-service
              port:
                number: 8080
    
