apiVersion: v1
kind: Pod
metadata:
  name: gin-server
  labels:
    app: go
spec:
  containers:
  - name: gin-server
    image: changsiheng/gin-server:week3
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","while kill -2 $(ps aux | grep gin-server| grep -v grep|awk '{print $1}'); do sleep 1; done"]
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 2
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
    ports:
      - containerPort: 8080
        name: http-go-svc


---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: http-go-svc